version: "3.9"
services:
  database-server:
    image: postgres
    # build: ./qmenta/database
    container_name: database-server
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=username
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - app_network
  server_app:
    build: ./server_app
    container_name: server_app
    environment:
      - POSTGRES_HOST=database-server
    restart: always
    ports:
      - "8000:8000"
    links:
      - database-server
    networks:
      - app_network
volumes:
  db:
    driver: local

networks:
  app_network:
    driver: bridge
