FROM python:latest
ENV DB_NAME database
ENV DB_HOSTNAME database
ENV DB_USERNAME username
ENV DB_PASSWORD secret
ENV DB_PORT 5432
WORKDIR /code
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY main.py main.py
COPY session_verifier.py session_verifier.py
COPY db/ db/
EXPOSE 8000
CMD ["python", "-u", "main.py"]
